"use strict";
/* SPECTRA dataset — simplified educational allocation tables.
   Band record: [loHz, hiHz, [services...], nick?, note?, flags?]
   Service CAPITALS = primary, lowercase = secondary (ITU convention).
   flags: "i" = ISM/unlicensed overlay, "q" = passive quiet band. */
const k = 1e3, M = 1e6, G = 1e9;

const FAMS = {
  bc:  { name: "Broadcasting" },
  mob: { name: "Mobile & cellular" },
  fx:  { name: "Fixed links" },
  mar: { name: "Maritime" },
  aero:{ name: "Aeronautical" },
  nav: { name: "Radar & navigation" },
  sat: { name: "Satellite" },
  ham: { name: "Amateur radio" },
  sci: { name: "Science & passive" },
  none:{ name: "Not allocated" },
};
const FAM_ORDER = ["bc","mob","fx","mar","aero","nav","sat","ham","sci","none"];
const FAM_RULES = [
  [/not allocated/, "none"],
  [/amateur/, "ham"],
  [/broadcasting/, "bc"],
  [/maritime/, "mar"],
  [/aeronautical/, "aero"],
  [/astronomy|earth exploration|space research|meteorological|standard frequency/, "sci"],
  [/space operations|inter-satellite/, "sat"],
  [/radionavigation-satellite/, "nav"],
  [/satellite/, "sat"],
  [/radiolocation|radionavigation|radiodetermination/, "nav"],
  [/citizens|mobile/, "mob"],
  [/fixed/, "fx"],
];
function famOf(svc){
  const t = svc.toLowerCase();
  for (const [re, f] of FAM_RULES) if (re.test(t)) return f;
  return "none";
}
function isPrimary(svc){
  const letters = svc.replace(/[^a-zA-Z]/g, "");
  return letters === letters.toUpperCase();
}

/* ───────────────────────── FCC / United States base table ─────────────────── */
const BASE = [
[3*k,9*k,["Not allocated"],"Natural radio","No allocations below 9 kHz — this is the realm of natural radio: lightning “sferics,” whistlers, and the dawn chorus of the magnetosphere. Listen with a coil and a soundcard."],
[9*k,14*k,["RADIONAVIGATION"],"","Long-wave hyperbolic navigation lived here (Omega, retired 1997). Waves at these frequencies duct between Earth and ionosphere clear around the planet."],
[14*k,59.75*k,["FIXED","MARITIME MOBILE"],"Submarine comms","VLF penetrates tens of metres of seawater — navies broadcast one-way traffic to submerged submarines (the US Navy’s Cutler, Maine array radiates 1.8 megawatts at 24 kHz)."],
[59.75*k,60.25*k,["STANDARD FREQUENCY AND TIME SIGNAL (60 kHz)"],"Radio-controlled clocks","WWVB in Colorado syncs millions of “atomic” wall clocks at 60 kHz; the UK’s MSF and Japan’s JJY share the frequency."],
[60.25*k,70*k,["FIXED","MARITIME MOBILE"]],
[70*k,90*k,["FIXED","MARITIME MOBILE","Radiolocation"]],
[90*k,110*k,["RADIONAVIGATION","Fixed"],"LORAN legacy","LORAN-C guided ships and aircraft from 100 kHz until GPS won; several nations keep the band for eLoran as a GPS backup."],
[110*k,130*k,["FIXED","MARITIME MOBILE"]],
[130*k,135.7*k,["FIXED","MARITIME MOBILE"]],
[135.7*k,137.8*k,["FIXED","MARITIME MOBILE","Amateur"],"2200 m amateur","The lowest ham band. With ~1 W radiated from garden-filling antennas, operators span oceans on multi-hour digital modes like WSPR."],
[137.8*k,160*k,["FIXED","MARITIME MOBILE"]],
[160*k,190*k,["FIXED"],"“LowFER” experiments","US hobbyists may run unlicensed beacons here — 1 W input, 15 m of antenna, and infinite patience."],
[190*k,285*k,["AERONAUTICAL RADIONAVIGATION"],"NDB beacons","Non-directional beacons still Morse their two-letter IDs to aircraft ADF receivers — 1930s navigation on the air in 2026."],
[285*k,325*k,["MARITIME RADIONAVIGATION (radiobeacons)","Aeronautical radionavigation"],"DGPS beacons","The old marine radiobeacon band, recycled to broadcast differential-GPS corrections."],
[325*k,435*k,["AERONAUTICAL RADIONAVIGATION"],"NDB beacons"],
[435*k,472*k,["MARITIME MOBILE"]],
[472*k,479*k,["MARITIME MOBILE","Amateur"],"630 m amateur","Granted at WRC-12 — the first new LF/MF amateur band in decades."],
[479*k,510*k,["MARITIME MOBILE"],"NAVTEX & old 500","NAVTEX prints navigational warnings at 490 and 518 kHz. 500 kHz was the international Morse distress frequency from Titanic until 1999, when GMDSS retired the radio officer."],
[510*k,525*k,["MOBILE","AERONAUTICAL RADIONAVIGATION"]],
[525*k,1705*k,["BROADCASTING"],"AM broadcast","The AM dial: channels every 10 kHz in the Americas (9 kHz elsewhere). At night the D-layer fades and skywave carries clear-channel stations across the continent. The 1610–1705 “expanded band” arrived in the 1990s."],
[1705*k,1800*k,["FIXED","MOBILE","RADIOLOCATION"]],
[1800*k,2000*k,["AMATEUR"],"160 m “Top Band”","Long, quiet winter nights reward patient CW operators — the closest ham radio gets to fly fishing."],
[2000*k,2170*k,["MARITIME MOBILE","FIXED"]],
[2170*k,2194*k,["MOBILE (distress and calling)"],"2182 kHz distress","Marine MF voice distress and calling — still watched by coast stations beyond VHF range."],
[2194*k,2495*k,["FIXED","MOBILE"]],
[2495*k,2505*k,["STANDARD FREQUENCY AND TIME SIGNAL (2500 kHz)"],"WWV 2.5 MHz","WWV has announced the time non-stop since 1923 — the oldest continuously operating radio station in the United States."],
[2505*k,2850*k,["FIXED","MOBILE"]],
[2850*k,3155*k,["AERONAUTICAL MOBILE (R)"],"Oceanic ATC","HF voice for transoceanic flights, organized into “families” of frequencies per ocean region."],
[3155*k,3400*k,["FIXED","Mobile"]],
[3400*k,3500*k,["AERONAUTICAL MOBILE (R)"]],
[3500*k,4000*k,["AMATEUR"],"80 m amateur","Regional nets by day, continental DX after dark."],
[4000*k,4063*k,["FIXED"]],
[4063*k,4438*k,["MARITIME MOBILE"],"","Ship-to-shore HF; 4125 kHz is a distress and calling channel."],
[4438*k,4650*k,["FIXED","MOBILE"]],
[4650*k,4750*k,["AERONAUTICAL MOBILE (R)"]],
[4750*k,4995*k,["FIXED","BROADCASTING"],"Tropical bands","Domestic shortwave for equatorial countries, where MW static from thunderstorms is brutal."],
[4995*k,5005*k,["STANDARD FREQUENCY AND TIME SIGNAL (5000 kHz)"],"WWV 5 MHz"],
[5005*k,5450*k,["FIXED","Mobile"],"60 m channels","US amateurs get five shared channels near 5.35 MHz inside this fixed-service stretch — the politest band in ham radio."],
[5450*k,5730*k,["AERONAUTICAL MOBILE (R)","AERONAUTICAL MOBILE (OR)"]],
[5730*k,5900*k,["FIXED"]],
[5900*k,6200*k,["BROADCASTING"],"49 m shortwave","Prime evening international broadcast band."],
[6200*k,6525*k,["MARITIME MOBILE"]],
[6525*k,6765*k,["AERONAUTICAL MOBILE (R)"]],
[6765*k,7000*k,["FIXED","Mobile"],"","Includes the 6.78 MHz ISM designation."],
[7000*k,7300*k,["AMATEUR"],"40 m amateur","The workhorse ham band — usable somewhere on Earth at any hour."],
[7300*k,7400*k,["BROADCASTING"],"41 m shortwave"],
[7400*k,8100*k,["FIXED","Broadcasting"]],
[8100*k,8815*k,["MARITIME MOBILE"]],
[8815*k,9040*k,["AERONAUTICAL MOBILE (R)"]],
[9040*k,9400*k,["FIXED"]],
[9400*k,9900*k,["BROADCASTING"],"31 m shortwave","The most crowded international broadcast band."],
[9900*k,9995*k,["FIXED"]],
[9995*k,10005*k,["STANDARD FREQUENCY AND TIME SIGNAL (10 MHz)"],"WWV 10 MHz"],
[10005*k,10100*k,["AERONAUTICAL MOBILE (R)"]],
[10100*k,10150*k,["FIXED","Amateur"],"30 m amateur","CW and digital only, by worldwide gentlemen’s agreement."],
[10150*k,11175*k,["FIXED","Mobile"]],
[11175*k,11400*k,["AERONAUTICAL MOBILE (OR)"],"Military HFGCS","11175 kHz carries the US military’s High Frequency Global Communications System — source of the cryptic Emergency Action Messages shortwave listeners collect."],
[11400*k,11600*k,["FIXED"]],
[11600*k,12100*k,["BROADCASTING"],"25 m shortwave"],
[12100*k,12230*k,["FIXED"]],
[12230*k,13200*k,["MARITIME MOBILE"]],
[13200*k,13360*k,["AERONAUTICAL MOBILE (R)","AERONAUTICAL MOBILE (OR)"]],
[13360*k,13410*k,["RADIO ASTRONOMY","Fixed"],"","Protected sliver for radio astronomy.","q"],
[13410*k,13570*k,["FIXED","Mobile"],"13.56 MHz ISM","Every contactless card tap, NFC phone payment, and warehouse RFID gate resonates at 13.56 MHz.","i"],
[13570*k,13870*k,["BROADCASTING"],"22 m shortwave"],
[13870*k,14000*k,["FIXED","Mobile"]],
[14000*k,14350*k,["AMATEUR"],"20 m amateur","The king of DX bands — worldwide propagation nearly every day of the solar cycle."],
[14350*k,14990*k,["FIXED","Mobile"]],
[14990*k,15010*k,["STANDARD FREQUENCY AND TIME SIGNAL (15 MHz)"],"WWV 15 MHz"],
[15010*k,15100*k,["AERONAUTICAL MOBILE (OR)"]],
[15100*k,15800*k,["BROADCASTING"],"19 m shortwave"],
[15800*k,16360*k,["FIXED"]],
[16360*k,17410*k,["MARITIME MOBILE"]],
[17410*k,17550*k,["FIXED"]],
[17550*k,17900*k,["BROADCASTING"],"16 m shortwave"],
[17900*k,18030*k,["AERONAUTICAL MOBILE (R)","AERONAUTICAL MOBILE (OR)"]],
[18030*k,18068*k,["FIXED"]],
[18068*k,18168*k,["AMATEUR"],"17 m amateur","A WARC-79 band: contest-free by agreement, famously relaxed."],
[18168*k,18780*k,["FIXED","Mobile"]],
[18780*k,18900*k,["MARITIME MOBILE"]],
[18900*k,19680*k,["FIXED","Broadcasting"]],
[19680*k,19800*k,["MARITIME MOBILE"]],
[19800*k,19990*k,["FIXED"]],
[19990*k,20010*k,["STANDARD FREQUENCY AND TIME SIGNAL (20 MHz)"],"WWV 20 MHz"],
[20010*k,21000*k,["FIXED","Mobile"]],
[21000*k,21450*k,["AMATEUR"],"15 m amateur","Comes alive with the sunspot cycle."],
[21450*k,21850*k,["BROADCASTING"],"13 m shortwave"],
[21850*k,22000*k,["FIXED","Aeronautical mobile (R)"]],
[22000*k,22855*k,["MARITIME MOBILE"]],
[22855*k,23200*k,["FIXED"]],
[23200*k,23350*k,["AERONAUTICAL MOBILE (OR)"]],
[23350*k,24890*k,["FIXED","LAND MOBILE"]],
[24890*k,24990*k,["AMATEUR"],"12 m amateur"],
[24990*k,25010*k,["STANDARD FREQUENCY AND TIME SIGNAL (25 MHz)"]],
[25010*k,25550*k,["FIXED","MOBILE except aeronautical"]],
[25550*k,25670*k,["RADIO ASTRONOMY"],"","","q"],
[25670*k,26100*k,["BROADCASTING"],"11 m shortwave","Little used now; some countries trialled DRM digital radio here."],
[26100*k,26965*k,["FIXED","MOBILE","Radiolocation"],"","Includes the 26.957–27.283 MHz ISM slice."],
[26965*k,27405*k,["MOBILE (Citizens Band)"],"CB radio","40 channels, 4 watts, no licence. The 1970s CB craze gave the world “10-4, good buddy” — and 27.12 MHz remains an ISM workhorse.","i"],
[27405*k,28000*k,["FIXED","MOBILE"]],
[28000*k,29700*k,["AMATEUR"],"10 m amateur","When the Sun cooperates, 100 milliwatts crosses the Atlantic."],
[29700*k,30000*k,["FIXED","MOBILE"]],
/* ── VHF ── */
[30*M,50*M,["FIXED","LAND MOBILE"],"VHF low band","“Low band” public-safety and highway radio — prone to summertime sporadic-E skip arriving from a thousand km away."],
[50*M,54*M,["AMATEUR"],"6 m “magic band”","Dead for months, then suddenly wide open to another continent. Hence the nickname."],
[54*M,72*M,["BROADCASTING"],"TV channels 2–4","Legacy VHF television — channel 2 begins at 54 MHz."],
[72*M,74.8*M,["FIXED","MOBILE"],"","Radio-control models and paging once ruled this sliver."],
[74.8*M,75.2*M,["AERONAUTICAL RADIONAVIGATION"],"75 MHz markers","Runway marker beacons fire a 75 MHz fan straight up; cockpit lamps blink blue-amber-white as you cross them."],
[75.2*M,76*M,["FIXED","MOBILE"]],
[76*M,88*M,["BROADCASTING"],"TV channels 5–6","Analog channel 6 audio sat at 87.75 MHz — listenable at the bottom of any FM radio (“Franken-FM” stations exploited this for years)."],
[88*M,108*M,["BROADCASTING"],"FM broadcast","The FM dial: 200 kHz channels, with 88–92 MHz reserved for noncommercial stations — why college radio lives on the left of the dial."],
[108*M,117.975*M,["AERONAUTICAL RADIONAVIGATION"],"VOR & ILS","VOR beacons and ILS localizers guide every instrument approach; pilots verify each by its Morse ident."],
[117.975*M,137*M,["AERONAUTICAL MOBILE (R)"],"VHF airband","Pilot–controller voice, still amplitude modulation so a stuck mic can’t fully block the channel. 121.5 MHz is “Guard,” monitored by every airliner."],
[137*M,138*M,["SPACE OPERATIONS","METEOROLOGICAL-SATELLITE (space-to-Earth)"],"Weather-sat downlink","Point a $30 SDR dongle at the sky: NOAA APT and Meteor-M weather imagery downlinks here on every pass."],
[138*M,144*M,["FIXED","MOBILE"],"","US military air-ground and land mobile."],
[144*M,148*M,["AMATEUR","AMATEUR-SATELLITE"],"2 m amateur","The most-used ham band on Earth: repeaters, ISS contacts, and 146.52 MHz simplex calling."],
[148*M,150.05*M,["MOBILE-SATELLITE (Earth-to-space)","FIXED","MOBILE"],"","Uplinks for little-LEO data constellations (Orbcomm)."],
[150.05*M,156*M,["MOBILE","FIXED"],"VHF land mobile","Police, fire, and business “high band” two-way radio."],
[156*M,157.45*M,["MARITIME MOBILE"],"Marine VHF","Channel 16 (156.8 MHz) is the international distress and calling channel, watched by every bridge and coast station."],
[157.45*M,161.575*M,["MOBILE","MARITIME MOBILE"],"","Railroads and land mobile interleave with marine duplex channels."],
[161.575*M,162.025*M,["MARITIME MOBILE"],"AIS","Every large vessel broadcasts position on AIS 1 and 2 (161.975 / 162.025 MHz) — the raw feed behind live ship-tracking maps."],
[162.025*M,174*M,["MOBILE","FIXED"],"NOAA Weather Radio","Seven channels around 162.5 MHz carry continuous forecasts and alerts to receivers that wake themselves for warnings."],
[174*M,216*M,["BROADCASTING"],"TV channels 7–13","VHF-high television — still prime digital-TV real estate after two repacks."],
[216*M,220*M,["FIXED","MARITIME MOBILE","Land mobile"],"","AMTS coastal telephony that never took off; now leased for narrowband data."],
[220*M,222*M,["FIXED","MOBILE"]],
[222*M,225*M,["AMATEUR"],"1.25 m amateur","A ham band that exists only in the Americas — ITU Region 1 never allocated it."],
[225*M,328.6*M,["FIXED","MOBILE"],"Military UHF airband","NATO air operations and carrier flight decks, in AM voice; 243 MHz is military Guard."],
[328.6*M,335.4*M,["AERONAUTICAL RADIONAVIGATION"],"ILS glideslope","Paired with the localizer below 118 MHz, this signal defines the 3° descent path to the runway threshold."],
[335.4*M,399.9*M,["FIXED","MOBILE"],"","More military air-ground, plus UHF follow-on satcom."],
[399.9*M,400.05*M,["RADIONAVIGATION-SATELLITE"]],
[400.05*M,400.15*M,["STANDARD FREQUENCY AND TIME SIGNAL-SATELLITE"]],
[400.15*M,406*M,["METEOROLOGICAL AIDS","METEOROLOGICAL-SATELLITE","SPACE RESEARCH"],"Radiosondes","Twice a day, ~900 weather balloons worldwide radio their ascent from here — the backbone of every forecast model."],
[406*M,406.1*M,["MOBILE-SATELLITE (Earth-to-space)"],"406 MHz rescue beacons","EPIRBs and PLBs burst to the SARSAT constellation; 50,000+ lives saved. Never test one indoors — the Air Force will find you."],
[406.1*M,410*M,["FIXED","MOBILE","RADIO ASTRONOMY"],"","","q"],
[410*M,420*M,["FIXED","MOBILE"],"","Federal land mobile."],
[420*M,450*M,["RADIOLOCATION","Amateur"],"70 cm amateur","Hams share 30 MHz with long-range surveillance radars (PAVE PAWS). 446.0 MHz is simplex calling."],
[450*M,470*M,["MOBILE","FIXED"],"UHF land mobile","Business radio plus the FRS/GMRS walkie-talkies at 462/467 MHz sold in every sporting-goods store."],
[470*M,608*M,["BROADCASTING"],"UHF TV 14–36","Post-repack digital TV heartland; unlicensed “white space” devices squeeze between stations."],
[608*M,614*M,["RADIO ASTRONOMY","Mobile-satellite"],"Channel 37","No TV station in North America may broadcast on channel 37 — it belongs to radio telescopes and hospital telemetry.","q"],
[614*M,698*M,["MOBILE","FIXED"],"600 MHz 5G (n71)","Auctioned away from broadcasters in 2017 for $19.8 B; now a nationwide low-band 5G layer."],
[698*M,806*M,["MOBILE","FIXED","BROADCASTING"],"700 MHz LTE","Freed by the 2009 analog-TV shutdown. LTE bands 12/13/14 — including FirstNet, the public-safety network."],
[806*M,896*M,["MOBILE","FIXED"],"800 MHz cellular","Where US cellular began (AMPS, 1983); now ESMR and LTE band 5."],
[896*M,902*M,["MOBILE","FIXED"],"","Narrowband PCS and paging."],
[902*M,928*M,["RADIOLOCATION","Fixed","Mobile","Amateur"],"915 MHz ISM","America’s unlicensed sub-GHz: LoRa, Z-Wave, toll tags, baby monitors — plus the 33 cm ham band. In Europe these exact frequencies are GSM uplink.","i"],
[928*M,960*M,["FIXED","MOBILE"],"","Paging and multi-address SCADA links."],
[960*M,1215*M,["AERONAUTICAL RADIONAVIGATION"],"DME / ADS-B / GPS L5","DME and TACAN interrogators, Mode-S at 1030/1090 MHz — every flight-tracker feeds on 1090 ADS-B — and GPS L5 at 1176.45 MHz."],
[1215*M,1240*M,["RADIONAVIGATION-SATELLITE","RADIOLOCATION"],"GPS L2","GPS L2 (1227.60) and GLONASS share with long-range air-route radars."],
[1240*M,1300*M,["RADIOLOCATION","Amateur"],"23 cm amateur","Hams and amateur TV dodge radars; Galileo E6 squeezes in at 1278.75."],
[1300*M,1350*M,["AERONAUTICAL RADIONAVIGATION","Radiolocation"],"","Long-range en-route surveillance radars."],
[1350*M,1400*M,["FIXED","MOBILE","RADIOLOCATION"]],
[1400*M,1427*M,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"Hydrogen line","All transmissions banned worldwide. 1420.4 MHz is the 21 cm line of neutral hydrogen — how we map the galaxy’s spiral arms, and where SETI listens first.","q"],
[1427*M,1435*M,["FIXED","MOBILE"]],
[1435*M,1525*M,["MOBILE (aeronautical telemetry)"],"Flight-test telemetry","Every new airframe streams its shakedown data here — Edwards AFB’s bread and butter."],
[1525*M,1559*M,["MOBILE-SATELLITE (space-to-Earth)"],"L-band satcom down","Inmarsat safety services to ships and airliners."],
[1559*M,1610*M,["RADIONAVIGATION-SATELLITE","AERONAUTICAL RADIONAVIGATION"],"GPS L1","1575.42 MHz: GPS L1, Galileo E1, BeiDou B1C. Arguably the most economically important 50 MHz in the spectrum — jam it and ships, planes, phones, and stock-exchange timestamps all feel it."],
[1610*M,1626.5*M,["MOBILE-SATELLITE (Earth-to-space)","RADIO ASTRONOMY"],"Iridium","Iridium’s 66 satellites serve phones here while astronomers try to hear the 1612 MHz OH line through the noise."],
[1626.5*M,1660.5*M,["MOBILE-SATELLITE (Earth-to-space)"],"Satphone uplink"],
[1660.5*M,1668*M,["RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"","OH maser lines.","q"],
[1668*M,1675*M,["METEOROLOGICAL AIDS","FIXED","MOBILE"]],
[1675*M,1695*M,["METEOROLOGICAL-SATELLITE (space-to-Earth)"],"GOES downlink","GOES weather imagery lands here — and the “Ligado” L-band fight raged next door for a decade."],
[1695*M,1710*M,["MOBILE"],"AWS-3 uplink"],
[1710*M,1780*M,["MOBILE"],"AWS/PCS uplink","The phone-to-tower half of AWS-1/3 (bands 4 and 66)."],
[1780*M,1850*M,["FIXED","MOBILE"],"","Federal systems, gradually cleared for sharing."],
[1850*M,1990*M,["MOBILE"],"PCS 1900","The 1995 PCS auctions — the FCC’s first big ones — built 2G here (band 2)."],
[1990*M,2025*M,["MOBILE","MOBILE-SATELLITE"]],
[2025*M,2110*M,["SPACE OPERATIONS","FIXED","MOBILE"],"","Spacecraft command uplinks and TV broadcast-auxiliary."],
[2110*M,2200*M,["MOBILE"],"AWS downlink","Tower-to-phone half of AWS (band 66)."],
[2200*M,2290*M,["SPACE OPERATIONS","FIXED"],"TT&C downlink","Satellite housekeeping telemetry — ISS voice and data included."],
[2290*M,2300*M,["SPACE RESEARCH (deep space)"],"Deep Space Network","Reserved for craft beyond 2 million km. Voyager 1’s 19-watt whisper arrives here at 10⁻¹⁸ watts.","q"],
[2300*M,2305*M,["Amateur"],"13 cm (lower)"],
[2305*M,2320*M,["MOBILE","FIXED"],"WCS"],
[2320*M,2345*M,["BROADCASTING-SATELLITE (sound)"],"SiriusXM","Satellite radio beamed straight to car antennas, with terrestrial repeaters for tunnels."],
[2345*M,2360*M,["MOBILE","FIXED"],"WCS"],
[2360*M,2390*M,["MOBILE (aeronautical telemetry)"],"","More flight-test telemetry."],
[2390*M,2400*M,["Amateur"],"13 cm (upper)"],
[2400*M,2483.5*M,["FIXED","MOBILE","RADIOLOCATION","Amateur"],"2.4 GHz ISM","The junk band that ate the world: Wi-Fi, Bluetooth, ZigBee, drones — all dodging microwave ovens at 2.45 GHz. Unlicensed because nobody wanted it; now priceless.","i"],
[2483.5*M,2495*M,["MOBILE-SATELLITE (space-to-Earth)"],"Globalstar down"],
[2495*M,2690*M,["MOBILE"],"2.5 GHz (n41)","Born as educational TV (EBS/BRS), collected by Sprint, now T-Mobile’s mid-band 5G spine."],
[2690*M,2700*M,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[2700*M,2900*M,["AERONAUTICAL RADIONAVIGATION","Radiolocation"],"ASR & NEXRAD","Airport surveillance radars, plus the WSR-88D weather radars that paint your rain map."],
[2900*M,3100*M,["RADIOLOCATION","MARITIME RADIONAVIGATION"],"Marine S-band radar"],
[3100*M,3300*M,["RADIOLOCATION"],"","Shipboard and airborne radars."],
[3300*M,3450*M,["RADIOLOCATION","Amateur"],"9 cm amateur","US hams lost most of 3.3–3.45 GHz in the 2020s reallocations — spectrum pressure in action."],
[3450*M,3550*M,["MOBILE","RADIOLOCATION"],"3.45 GHz 5G","Auction 110 (2021): $22.5 B for 100 MHz of mid-band, time-shared with DoD radars."],
[3550*M,3700*M,["MOBILE (CBRS)","RADIOLOCATION"],"CBRS","A three-tier sharing experiment: Navy radars first, priority licensees second, anyone with a certified radio third — refereed in real time by cloud spectrum controllers."],
[3700*M,3980*M,["MOBILE","FIXED-SATELLITE (space-to-Earth)"],"C-band 5G (n77)","The $81 B auction. Satellite TV squeezed upward; radar-altimeter interference fears delayed airline rollouts in 2022."],
[3980*M,4200*M,["FIXED-SATELLITE (space-to-Earth)","FIXED"],"C-band satellite","Classic big-dish downlink — rain-fade-proof and beloved by broadcasters."],
[4200*M,4400*M,["AERONAUTICAL RADIONAVIGATION (radio altimeters)"],"Radar altimeters","Every airliner measures its height above ground here on final approach — the reason the C-band 5G fight mattered."],
[4400*M,4940*M,["FIXED","MOBILE"],"","Military trunking and tactical comms."],
[4940*M,4990*M,["MOBILE"],"4.9 GHz public safety"],
[4990*M,5000*M,["RADIO ASTRONOMY"],"","","q"],
[5000*M,5150*M,["AERONAUTICAL RADIONAVIGATION","AERONAUTICAL MOBILE-SATELLITE (R)"],"","Microwave landing systems (mostly leapfrogged by GPS) and future airport datalinks."],
[5150*M,5250*M,["MOBILE","FIXED-SATELLITE (Earth-to-space)"],"Wi-Fi U-NII-1","5 GHz Wi-Fi’s bottom 100 MHz, shared with satellite feeder uplinks.","i"],
[5250*M,5350*M,["RADIOLOCATION","EARTH EXPLORATION-SATELLITE (active)","MOBILE"],"Wi-Fi U-NII-2 (DFS)","Wi-Fi must listen for radar and vacate — Dynamic Frequency Selection. Spaceborne SAR images the Earth through the same window.","i"],
[5350*M,5470*M,["EARTH EXPLORATION-SATELLITE (active)","AERONAUTICAL RADIONAVIGATION"],"The Wi-Fi gap","No Wi-Fi here: airborne weather radar and satellite SAR won that argument."],
[5470*M,5725*M,["RADIOLOCATION","MARITIME RADIONAVIGATION","MOBILE"],"Wi-Fi U-NII-2C (DFS)","More radar-dodging Wi-Fi; Terminal Doppler Weather Radars near 5.6 GHz trigger the vacate rule.","i"],
[5725*M,5850*M,["RADIOLOCATION","MOBILE","Amateur"],"5.8 GHz ISM","Wi-Fi’s upper band, drone FPV video, and toll tags; hams hold 5650–5925 as secondary.","i"],
[5850*M,5925*M,["MOBILE (ITS)","FIXED-SATELLITE (Earth-to-space)"],"C-V2X","Reserved 20 years for talking cars that never shipped; re-split in 2020 — 45 MHz to Wi-Fi, 30 MHz to cellular-V2X."],
[5925*M,7125*M,["FIXED","FIXED-SATELLITE (Earth-to-space)","MOBILE"],"6 GHz Wi-Fi 6E/7","In 2020 the FCC opened all 1200 MHz to unlicensed Wi-Fi — low-power indoor, sharing with thousands of licensed microwave links. The largest unlicensed grant ever made.","i"],
[7125*M,7250*M,["FIXED"],"","Federal microwave; eyed for future sharing."],
[7250*M,7750*M,["FIXED-SATELLITE (space-to-Earth)","FIXED"],"X-band milsatcom down"],
[7750*M,7900*M,["METEOROLOGICAL-SATELLITE (space-to-Earth)"]],
[7900*M,8400*M,["FIXED-SATELLITE (Earth-to-space)","EARTH EXPLORATION-SATELLITE (space-to-Earth)"],"X-band up / EO down","Milsatcom uplinks; 8025–8400 rains down imagery from Landsat, Sentinel, and friends."],
[8400*M,8500*M,["SPACE RESEARCH (space-to-Earth)"],"Deep-space X-band","The DSN’s main downlink: Mars rovers, Voyager, and every interplanetary probe.","q"],
[8500*M,9000*M,["RADIOLOCATION"],"X-band radar"],
[9000*M,9200*M,["AERONAUTICAL RADIONAVIGATION","Radiolocation"],"Precision approach radar"],
[9200*M,9300*M,["RADIOLOCATION","MARITIME RADIONAVIGATION"],"SART","9 GHz search-and-rescue transponders paint a dotted trail to survivors on any ship’s radar."],
[9300*M,9500*M,["AERONAUTICAL RADIONAVIGATION","RADIOLOCATION"],"Airborne weather radar","The radar in every airliner’s nose (9.375 GHz)."],
[9500*M,10000*M,["RADIOLOCATION"],"Marine X-band radar"],
[10*G,10.5*G,["RADIOLOCATION","Amateur"],"3 cm amateur / X-band","10 GHz ham microwave (rain-scatter DX is a real sport) and 10.525 GHz police speed radar."],
[10.5*G,10.7*G,["RADIOLOCATION","FIXED"]],
[10.7*G,11.7*G,["FIXED-SATELLITE (space-to-Earth)","FIXED"],"Ku downlink","Ku satellite downlink — Starlink terminals receive 10.7–12.7 GHz — plus terrestrial microwave backbones."],
[11.7*G,12.2*G,["FIXED-SATELLITE (space-to-Earth)"],"Ku DTH","North American direct-to-home satellite territory."],
[12.2*G,12.7*G,["BROADCASTING-SATELLITE"],"DBS","DirecTV and DISH beam from geostationary orbit — 22,236 miles per hop."],
[12.7*G,13.25*G,["FIXED","MOBILE","FIXED-SATELLITE (Earth-to-space)"],"ENG / Ku uplink","TV news trucks and satellite uplinks."],
[13.25*G,13.4*G,["AERONAUTICAL RADIONAVIGATION (doppler)"]],
[13.4*G,13.75*G,["RADIOLOCATION"],"Ku radar"],
[13.75*G,14*G,["FIXED-SATELLITE (Earth-to-space)","RADIOLOCATION"]],
[14*G,14.5*G,["FIXED-SATELLITE (Earth-to-space)"],"VSAT / Starlink up","The uplink half of Ku: airline Wi-Fi antennas and Starlink dishes transmit here."],
[14.5*G,15.35*G,["FIXED","MOBILE"],"","Military point-to-point."],
[15.35*G,15.4*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[15.4*G,15.7*G,["AERONAUTICAL RADIONAVIGATION"]],
[15.7*G,17.3*G,["RADIOLOCATION"],"Ku radars"],
[17.3*G,17.7*G,["FIXED-SATELLITE (Earth-to-space)","Radiolocation"],"BSS feeder up"],
[17.7*G,18.3*G,["FIXED","FIXED-SATELLITE (space-to-Earth)"],"18 GHz links"],
[18.3*G,18.8*G,["FIXED-SATELLITE (space-to-Earth)"],"Ka down"],
[18.8*G,19.3*G,["FIXED-SATELLITE (space-to-Earth)"],"NGSO Ka down","Reserved for non-geostationary fleets — Starlink and Kuiper gateway downlinks."],
[19.3*G,19.7*G,["FIXED-SATELLITE","MOBILE-SATELLITE"],"MSS feeders"],
[19.7*G,20.2*G,["FIXED-SATELLITE (space-to-Earth)","MOBILE-SATELLITE"],"Ka consumer down","Satellite home-internet downlink (Viasat, HughesNet)."],
[20.2*G,21.2*G,["FIXED-SATELLITE","MOBILE-SATELLITE (government)"],"WGS milsatcom"],
[21.2*G,22*G,["EARTH EXPLORATION-SATELLITE","FIXED","MOBILE"]],
[22*G,23.6*G,["FIXED","MOBILE"],"23 GHz links","Short urban microwave hops; the 22.235 GHz water-vapor line makes rain fade fierce."],
[23.6*G,24*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"Water-vapor sounding","Passive-only: weather satellites sense humidity at 23.8 GHz. The 2019 fight over 5G emissions next door went all the way to WRC-19.","q"],
[24*G,24.25*G,["RADIOLOCATION","Amateur"],"24 GHz ISM","Automatic door openers, K-band police radar (24.15), and a ham band.","i"],
[24.25*G,24.45*G,["MOBILE"],"24 GHz 5G (n258)","mmWave 5G: enormous bandwidth, tiny range — blocked by your own hand."],
[24.45*G,24.75*G,["MOBILE","INTER-SATELLITE"]],
[24.75*G,25.25*G,["MOBILE","FIXED-SATELLITE (Earth-to-space)"],"n258 upper"],
[25.25*G,27.5*G,["FIXED","MOBILE","INTER-SATELLITE","EARTH EXPLORATION-SATELLITE (space-to-Earth)"],"26 GHz","Europe’s pioneer mmWave 5G band; in the US, satellite data downlinks and fixed links."],
[27.5*G,28.35*G,["MOBILE","FIXED-SATELLITE (Earth-to-space)"],"28 GHz 5G (n261)","Verizon’s original mmWave 5G, shared with satellite uplinks."],
[28.35*G,29.1*G,["FIXED-SATELLITE (Earth-to-space)"],"Ka up (ESIM)","Uplinks from earth stations in motion — planes, ships, trains."],
[29.1*G,29.5*G,["FIXED-SATELLITE (Earth-to-space)","MOBILE-SATELLITE"]],
[29.5*G,30*G,["FIXED-SATELLITE (Earth-to-space)","MOBILE-SATELLITE"],"Ka consumer up"],
[30*G,31*G,["FIXED-SATELLITE (Earth-to-space)","MOBILE-SATELLITE (government)"]],
[31*G,31.3*G,["FIXED","MOBILE"]],
[31.3*G,31.8*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"","Another protected passive window.","q"],
[31.8*G,33.4*G,["RADIONAVIGATION"],"32 GHz","Also the DSN’s future deep-space Ka downlink."],
[33.4*G,36*G,["RADIOLOCATION"],"Ka radar","35 GHz cloud-profiling radars and missile seekers."],
[36*G,37*G,["EARTH EXPLORATION-SATELLITE","FIXED","MOBILE"]],
[37*G,40*G,["MOBILE","FIXED","FIXED-SATELLITE"],"39 GHz 5G (n260)","AT&T and Verizon mmWave; 37.0–37.6 is a shared federal/commercial experiment."],
[40*G,42*G,["FIXED-SATELLITE (space-to-Earth)","BROADCASTING-SATELLITE"],"V-band down"],
[42*G,43.5*G,["FIXED","MOBILE"]],
[43.5*G,47*G,["MOBILE-SATELLITE","RADIONAVIGATION-SATELLITE"],"Milsatcom V-band"],
[47*G,47.2*G,["AMATEUR","AMATEUR-SATELLITE"],"47 GHz amateur"],
[47.2*G,48.2*G,["MOBILE"],"47 GHz 5G (n262)"],
[48.2*G,50.2*G,["FIXED-SATELLITE (Earth-to-space)"],"V-band up"],
[50.2*G,50.4*G,["EARTH EXPLORATION-SATELLITE (passive)","SPACE RESEARCH (passive)"],"","Oxygen-temperature sounding.","q"],
[50.4*G,52.6*G,["FIXED","MOBILE","FIXED-SATELLITE"]],
[52.6*G,54.25*G,["EARTH EXPLORATION-SATELLITE (passive)","SPACE RESEARCH (passive)"],"O₂ sounding","Weather models ingest these passive soundings every six hours.","q"],
[54.25*G,57*G,["INTER-SATELLITE","EARTH EXPLORATION-SATELLITE (passive)"]],
[57*G,64*G,["FIXED","MOBILE","INTER-SATELLITE","RADIOLOCATION"],"60 GHz WiGig","Oxygen soaks up 15 dB/km at 60 GHz — signals die fast, so everyone can reuse the band. Unlicensed 57–71 GHz hosts WiGig, wireless HDMI, and gesture radar.","i"],
[64*G,71*G,["FIXED","MOBILE","INTER-SATELLITE"],"60 GHz upper","US unlicensed extension to 71 GHz.","i"],
[71*G,76*G,["FIXED","FIXED-SATELLITE","MOBILE"],"E-band","Light-licensed 70/80 GHz “wireless fiber” — multi-gigabit backhaul hops."],
[76*G,81*G,["RADIOLOCATION"],"77 GHz car radar","Every modern car’s adaptive cruise and emergency braking radar lives here."],
[81*G,86*G,["FIXED","FIXED-SATELLITE","MOBILE"],"E-band upper"],
[86*G,92*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"W-band window","Passive-only, worldwide.","q"],
[92*G,95*G,["FIXED","MOBILE","RADIOLOCATION"],"94 GHz cloud radar","CloudSat profiled clouds at 94 GHz; airports use it to see through fog."],
[95*G,100*G,["RADIOLOCATION","RADIONAVIGATION"]],
[100*G,102*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[102*G,109.5*G,["FIXED","MOBILE"]],
[109.5*G,111.8*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY","SPACE RESEARCH (passive)"],"","","q"],
[111.8*G,114.25*G,["FIXED","MOBILE"]],
[114.25*G,122.25*G,["EARTH EXPLORATION-SATELLITE (passive)","INTER-SATELLITE","FIXED","MOBILE"],"118 GHz O₂ line"],
[122.25*G,123*G,["FIXED","MOBILE","Amateur"],"122 GHz amateur","ISM at 122.5 GHz; hams have bridged 100+ km up here.","i"],
[123*G,130*G,["FIXED-SATELLITE","RADIONAVIGATION-SATELLITE"]],
[130*G,134*G,["RADIO ASTRONOMY","INTER-SATELLITE"]],
[134*G,141*G,["RADIOLOCATION","Amateur"],"134 GHz amateur"],
[141*G,148.5*G,["FIXED","MOBILE","RADIOLOCATION"]],
[148.5*G,151.5*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[151.5*G,164*G,["RADIOLOCATION","FIXED"]],
[164*G,167*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[167*G,174.8*G,["FIXED","MOBILE","INTER-SATELLITE"]],
[174.8*G,191.8*G,["EARTH EXPLORATION-SATELLITE (passive)","INTER-SATELLITE"],"183 GHz water line","The strongest water-vapor line — hurricane-watching sounders stare at it.","q"],
[191.8*G,200*G,["INTER-SATELLITE","EARTH EXPLORATION-SATELLITE (passive)"]],
[200*G,209*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","Passive-only.","q"],
[209*G,226*G,["FIXED","FIXED-SATELLITE","RADIO ASTRONOMY"]],
[226*G,231.5*G,["RADIOLOCATION"]],
[231.5*G,235*G,["FIXED","FIXED-SATELLITE"]],
[235*G,238*G,["EARTH EXPLORATION-SATELLITE (passive)","FIXED-SATELLITE"]],
[238*G,241*G,["RADIOLOCATION","RADIONAVIGATION"]],
[241*G,248*G,["RADIOLOCATION","Amateur"],"","ISM at 245 GHz.","i"],
[248*G,250*G,["AMATEUR","AMATEUR-SATELLITE"],"Highest amateur band"],
[250*G,252*G,["EARTH EXPLORATION-SATELLITE (passive)","RADIO ASTRONOMY"],"","","q"],
[252*G,275*G,["FIXED","MOBILE","RADIONAVIGATION-SATELLITE"]],
[275*G,300*G,["Not allocated"],"THz frontier","Above 275 GHz the international table simply ends — only passive bands are “identified.” 6G researchers prototype terabit links up here, where the map runs out."],
];
